[package]
name = "mcai_worker_sdk"
version = "0.10.3"
authors = [
  "Marc-Antoine Arnaud <maarnaud@media-io.com>",
  "Valentin Noel <valentin.noel@media-io.com>"
]
description = "AMQP Worker to listen and provide trait to process message"
keywords = ["AMQP", "micro-service"]
license = "MIT"
repository = "https://github.com/media-cloud-ai/mcai_worker_sdk"
homepage = "https://github.com/media-cloud-ai/mcai_worker_sdk"
documentation = "https://docs.rs/mcai_worker_sdk"
readme = "README.md"
edition = "2018"

[dependencies]
amq-protocol = "=6.0.0-rc4"
amq-protocol-types = "=6.0.0-rc5"
amq-protocol-uri = "=6.0.0-rc4"
chrono = {version = "0.4", features = ["serde"]}
env_logger = "^0.7"
failure = "^0.1"
futures-util = "^0.3"
futures-executor = "^0.3"
futures-core = "^0.3"
lapin = "=1.0.0-rc1"
log = "0.4.5"
reqwest = { version = "0.10", features = ["blocking", "json"] }
semver = { version = "0.9", features = ["serde"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
sysinfo = "^0.14"
tokio = "^0.2"
uuid = { version = "^0.8", features = ["serde", "v4"] }

[dev-dependencies]
assert_matches = "1.3.0"
mockito = "0.25"

[build-dependencies]
built = "0.4"
